const ModuleFederationPlugin = require("webpack/lib/container/ModuleFederationPlugin");
const mf = require("@angular-architects/module-federation/webpack");
const CopyWebpackPlugin = require("copy-webpack-plugin");
const path = require("path");
const webpack = require("webpack");
const fs = require("fs");
const share = mf.share;
const shareAll = mf.shareAll;

const sharedMappings = new mf.SharedMappings();
sharedMappings.register(path.join(__dirname, "tsconfig.json"), [
  /* mapped paths to share */
]);

/**
 * Webpack plugin that auto-generates component imports in customComponentMappings.ts.
 * Scans the components directory before each compilation so `ng build` and `ng serve`
 * both pick up new components without a separate prebuild step.
 */
class NdeComponentDiscoveryPlugin {
  constructor(options = {}) {
    this.componentsDir =
      options.componentsDir || path.resolve(__dirname, "src/app/components");
    this.mappingsFile =
      options.mappingsFile ||
      path.resolve(
        __dirname,
        "src/app/custom1-module/customComponentMappings.ts",
      );
    this.mappingsDir = path.dirname(this.mappingsFile);
  }

  apply(compiler) {
    compiler.hooks.beforeCompile.tapAsync(
      "NdeComponentDiscoveryPlugin",
      (params, callback) => {
        try {
          const imports = this.findComponentFiles(this.componentsDir).map(
            (file) => {
              let rel = path
                .relative(this.mappingsDir, file)
                .replace(/\\/g, "/");
              if (!rel.startsWith(".")) rel = "./" + rel;
              return `import '${rel.replace(/\.ts$/, "")}';`;
            },
          );

          const content = `import { getComponentRegistry } from '../decorators/nde-component.decorator';

// Auto-generated component imports — DO NOT EDIT
// Generated by NdeComponentDiscoveryPlugin (webpack.config.js)
${imports.join("\n")}

// Export the auto-populated registry
export const selectorComponentMap = getComponentRegistry();

// Log registry contents for debugging
console.log('[ComponentMappings] Registry size:', selectorComponentMap.size);
console.log('[ComponentMappings] Registered components:', Array.from(selectorComponentMap.keys()));
`;

          // Only write when content actually changed to avoid unnecessary recompilation
          const existing = fs.existsSync(this.mappingsFile)
            ? fs.readFileSync(this.mappingsFile, "utf8")
            : "";
          if (existing !== content) {
            fs.writeFileSync(this.mappingsFile, content);
            console.log(
              `[NdeComponentDiscovery] Updated mappings with ${imports.length} component(s)`,
            );
          }
        } catch (err) {
          console.error("[NdeComponentDiscovery] Error:", err);
        }
        callback();
      },
    );
  }

  findComponentFiles(dir, files = []) {
    if (!fs.existsSync(dir)) return files;
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        this.findComponentFiles(full, files);
      } else if (
        entry.name.endsWith(".component.ts") &&
        !entry.name.endsWith(".spec.ts")
      ) {
        files.push(full);
      }
    }
    return files;
  }
}

/**
 * Webpack plugin that auto-generates interceptor imports in _registry.ts.
 * Scans the interceptors directory before each compilation so `ng build` and `ng serve`
 * both pick up new interceptors without manual imports in app.module.ts.
 */
class NdeInterceptorDiscoveryPlugin {
  constructor(options = {}) {
    this.interceptorsDir =
      options.interceptorsDir ||
      path.resolve(__dirname, "src/app/interceptors");
    this.registryFile =
      options.registryFile ||
      path.resolve(__dirname, "src/app/interceptors/_registry.ts");
    this.registryDir = path.dirname(this.registryFile);
  }

  apply(compiler) {
    compiler.hooks.beforeCompile.tapAsync(
      "NdeInterceptorDiscoveryPlugin",
      (params, callback) => {
        try {
          const imports = this.findInterceptorFiles(this.interceptorsDir).map(
            (file) => {
              let rel = path
                .relative(this.registryDir, file)
                .replace(/\\/g, "/");
              if (!rel.startsWith(".")) rel = "./" + rel;
              return `import '${rel.replace(/\.ts$/, "")}';`;
            },
          );

          const content = `// Auto-generated interceptor imports — DO NOT EDIT
// Generated by NdeInterceptorDiscoveryPlugin (webpack.config.js)
${imports.join("\n")}
`;

          const existing = fs.existsSync(this.registryFile)
            ? fs.readFileSync(this.registryFile, "utf8")
            : "";
          if (existing !== content) {
            fs.writeFileSync(this.registryFile, content);
            console.log(
              `[NdeInterceptorDiscovery] Updated registry with ${imports.length} interceptor file(s)`,
            );
          }
        } catch (err) {
          console.error("[NdeInterceptorDiscovery] Error:", err);
        }
        callback();
      },
    );
  }

  findInterceptorFiles(dir, files = []) {
    if (!fs.existsSync(dir)) return files;
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        this.findInterceptorFiles(full, files);
      } else if (
        entry.name.endsWith(".interceptor.ts") &&
        !entry.name.endsWith(".spec.ts") &&
        entry.name !== "_registry.ts"
      ) {
        files.push(full);
      }
    }
    return files;
  }
}

module.exports = {
  context: path.resolve(__dirname), // Sets the context to the directory where webpack.config.js is
  output: {
    uniqueName: "customModule",
    publicPath: "auto",
  },
  optimization: {
    minimize: true,
    runtimeChunk: false,
  },
  resolve: {
    alias: {
      ...sharedMappings.getAliases(),
    },
  },
  experiments: {
    outputModule: true,
  },
  module: {
    rules: [
      // ... other rules ...
      {
        test: /\.(png|jpe?g|gif|svg)$/i,
        type: "asset/resource",
      },
    ],
  },
  plugins: [
    new NdeComponentDiscoveryPlugin(),
    new NdeInterceptorDiscoveryPlugin(),
    new CopyWebpackPlugin({
      patterns: [
        {
          from: "src/assets",
          to: "assets",
          noErrorOnMissing: true,
          globOptions: {
            ignore: [
              "**/.gitkeep", // Make sure this matches exactly the files you want to exclude
              "**/.*", // This pattern excludes all hidden files
            ],
          },
        }, // Adjust the paths as needed
      ],
    }),
    // DISABLE ngDevMode as it is not needed in a remoteEntry work around for issue: https://github.com/angular-architects/module-federation-plugin/issues/458
    // new webpack.DefinePlugin({
    //   ngDevMode: "undefined",
    // }),
    // END DISABLE ngDevMode as it is not needed in a remoteEntry
    new ModuleFederationPlugin({
      library: { type: "module" },

      // For remotes (please adjust)
      name: "customModule",
      filename: "remoteEntry.js",
      exposes: {
        "./custom-module": "./src/bootstrap.ts",
      },

      // For hosts (please adjust)
      // remotes: {
      //     "mfe1": "http://localhost:3000/remoteEntry.js",

      // },

      shared: share({
        "@angular/core":              { requiredVersion: "auto" },
        "@angular/common":            { requiredVersion: "auto" },
        "@angular/router":            { requiredVersion: "auto" },
        "rxjs":                       { requiredVersion: "auto" },
        "@angular/common/http":       { requiredVersion: "auto" },
        "@angular/platform-browser":  { requiredVersion: "auto" },
        "@ngx-translate/core":        { singleton: true },
        "@ngrx/store":                { singleton: true },        
        "@libis/primo-shared-state":  { singleton: true, strictVersion: false },
        ...sharedMappings.getDescriptors(),
      }),
    }),
    sharedMappings.getPlugin(),
  ],
};
