FROM node:20-bookworm

# USER node:node
# WORKDIR /app  
 
# ENV PATH=/app/node_modules/.bin:$PATH
# ENV NODE_OPTIONS=--openssl-legacy-provider

# EXPOSE 4200
# EXPOSE 4201

RUN npm install -g @angular/cli@18
