import { getComponentRegistry } from '../decorators/nde-component.decorator';

// Auto-generated component imports - DO NOT EDIT
// Generated by NdeComponentDiscoveryPlugin
// Freeze key: undefined
// Build target: view
// View: kuleuven



// Export the auto-populated registry
export const selectorComponentMap = getComponentRegistry();

console.log('[ComponentMappings] Build target:', 'view');
console.log('[ComponentMappings] View:', 'kuleuven');
console.log('[ComponentMappings] Registry size:', selectorComponentMap.size);
console.log('[ComponentMappings] Registered components:', Array.from(selectorComponentMap.keys()));
