import { getComponentRegistry } from '../decorators/nde-component.decorator';

// Auto-generated component imports - DO NOT EDIT
// Generated by NdeComponentDiscoveryPlugin
// Freeze key: undefined
// Build target: central
// View: 

import '../components/central/altmetric/altmetric.component';
import '../components/central/auto-login-first-option/auto-login-first-option.component';
import '../components/central/custom-alert-message/custom-alert-message.component';
import '../components/central/custom-static-footer/custom-static-footer.component';
import '../components/central/custom-view-logo/custom-view-logo.component';
import '../components/central/ill-link/ill-link.component';
import '../components/central/libis-permalink/libis-permalink.component';
import '../components/central/libis-search-also/libis-search-also.component';
import '../components/central/libis-source-icon/libis-source-icon.component';
import '../components/central/pay-fines/pay-fines.component';
import '../components/central/physical-availability-line/physical-availability-line.component';
import '../components/central/search-stats/search-stats.component';

// Export the auto-populated registry
export const selectorComponentMap = getComponentRegistry();

console.log('[ComponentMappings] Build target:', 'central');
console.log('[ComponentMappings] View:', '');
console.log('[ComponentMappings] Registry size:', selectorComponentMap.size);
console.log('[ComponentMappings] Registered components:', Array.from(selectorComponentMap.keys()));
