import { getComponentRegistry } from '../decorators/nde-component.decorator';

// Auto-generated component imports — DO NOT EDIT
// Generated by NdeComponentDiscoveryPlugin (webpack.config.js)
import '../components/libis-availability/libis-availability.component';
import '../components/libis-password-note/libis-password-note.component';
import '../components/libis-permalink/libis-permalink.component';
import '../components/search-stats/search-stats.component';

// Export the auto-populated registry
export const selectorComponentMap = getComponentRegistry();

// Log registry contents for debugging
console.log('[ComponentMappings] Registry size:', selectorComponentMap.size);
console.log('[ComponentMappings] Registered components:', Array.from(selectorComponentMap.keys()));
